/* --------------------------------------------------------------------------------
 #
 #	4DPlugin.h
 #	source generated by 4D Plugin Wizard
 #	Project : Preview
 #	author : miyako
 #	2017/10/08
 #
 # --------------------------------------------------------------------------------*/



// --- Preview
void PREVIEW_DOCUMENT_TO_PDF(sLONG_PTR *pResult, PackagePtr pParams);
